### ISSUE TITLE
ValueError: dict contains fields not in fieldnames: 'ipc_class_level'

### ISSUE THREAD

**Issue by mateusrangel** [cortext/patstat#3]
python 03_02_abstract_from_ipc.py 
Traceback (most recent call last):
  File "03_02_abstract_from_ipc.py", line 162, in <module>
    dicToCsv(ofname, csv_columns, dict_data['ipc'])
  File "03_02_abstract_from_ipc.py", line 98, in dicToCsv
    writer.writerow(data)
  File "/usr/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/lib/python2.7/csv.py", line 148, in _dict_to_list
    + ", ".join([repr(x) for x in wrong_fields]))
ValueError: dict contains fields not in fieldnames: 'ipc_class_level'

**Comment by mateusrangel** [comment]
This happens when i run the 03_02_abstract_from_ipc.py script

**Comment by gnupablo** [comment]
Thanks for report it. 

I'm going to test it tomorrow, and I will let you know what could causing this error.
